### ISSUE TITLE
Installed iqoption api completed , but error after run script

### ISSUE THREAD

**Issue by sutsake** [iqoptionapi/iqoptionapi#91]
I Installed iqoption api completed , but error after run script

my script have only line 1 line for test below : test.py
from iqoptionapi.stable_api import IQ_Option

after i run my script by : python test.py  I got error message below , please help to tech me how to solve ?

C:\iqbot>python test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from iqoptionapi.stable_api import IQ_Option
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\iqoptionapi-7.1.1-py3.7.egg\iqoptionapi\stable_api.py", line 2, in <module>
    from iqoptionapi.api import IQOptionAPI
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\iqoptionapi-7.1.1-py3.7.egg\iqoptionapi\api.py", line 7, in <module>
    import requests
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests-2.31.0-py3.7.egg\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3-2.0.4-py3.7.egg\urllib3\__init__.py", line 13, in <module>
    from . import exceptions
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3-2.0.4-py3.7.egg\urllib3\exceptions.py", line 7, in <module>
    from http.client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'http.client'

**Comment by davideduardotech** [comment]
consegui resolver esse erro ai instalando a versão 1.26.6 do urllib3

> `pip install urllib3==1.26.6`
